name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'
          - '2.7.7'
    
    services:
      redis:
        image: redis-${{ matrix.ruby }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 2

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install the bundler
      run: bundle

    - name: Run rspec
      run: bundle exec rspec
      env:
          REDIS_URL: redis://redis-${{ matrix.ruby }}:6379/1
          REDIS_NO_FLUSH: true
